package elite.intel.gameapi;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import elite.intel.ai.mouth.subscribers.events.AiVoxResponseEvent;
import elite.intel.gameapi.journal.EventRegistry;
import elite.intel.gameapi.journal.events.BaseEvent;
import elite.intel.session.PlayerSession;
import elite.intel.ui.event.AppLogEvent;
import elite.intel.util.json.GsonFactory;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.Comparator;
import java.util.concurrent.TimeUnit;

/**
 * The JournalParser class is responsible for monitoring and parsing journal log files
 * generated by the Elite Dangerous game. It continuously watches a specified directory
 * for changes to log files, reads journal entries, processes event data, and publishes
 * events to the EventBusManager for further handling.
 * <p>
 * This class is implemented as a Runnable to allow asynchronous execution in a separate
 * thread. It uses a WatchService to detect file modifications or new files in the directory
 * and processes journal data incrementally. Parsing includes handling JSON-based event data
 * and publishing it to the event bus for downstream processing.
 * <p>
 * Key Features:
 * - Watches a specified directory for log file creation and modification.
 * - Reads and processes journal entries with support for handling UTF-8 BOM.
 * - Publishes parsed event objects to a central event bus for handling.
 * - Handles safe shutdown and interruption of the parser thread.
 * <p>
 * Threading Behavior:
 * - The class relies on a dedicated worker thread started via the start method.
 * - The stop method is used to request the thread to terminate, ensuring a clean shutdown.
 * <p>
 * Error Handling:
 * - Catches and logs exceptions such as I/O issues or unexpected parsing errors.
 * - Publishes error-related events (e.g., AppLogEvent) to notify other components.
 */
public class JournalParser implements Runnable {
    private static final Logger log = LogManager.getLogger(JournalParser.class);
    private  Path journalDir;
    private Thread processingThread;
    private volatile boolean isRunning;

    public JournalParser() {
    }

    public synchronized void start() {
        journalDir = PlayerSession.getInstance().getJournalPath();
        if (processingThread != null && processingThread.isAlive()) {
            log.warn("JournalParser is already running");
            return;
        }
        isRunning = true;
        processingThread = new Thread(this, "JournalParserThread");
        processingThread.start();
        log.info("JournalParser started");
    }

    public synchronized void stop() {
        if (processingThread == null || !processingThread.isAlive()) {
            log.warn("JournalParser is not running");
            return;
        }
        isRunning = false;
        processingThread.interrupt();
        try {
            processingThread.join(5000); // Wait up to 5 seconds for clean shutdown
            log.info("JournalParser stopped");
        } catch (InterruptedException e) {
            log.warn("Interrupted while waiting for JournalParser to stop");
            Thread.currentThread().interrupt(); // Restore interrupted status
        }
        processingThread = null;
    }

    @Override
    public void run() {
        try {
            startReading();
        } catch (IOException e) {
            log.error("IOException in JournalParser", e);
            EventBusManager.publish(new AppLogEvent("Please check jounral directory"));
        } catch (InterruptedException e) {
            log.info("JournalParser interrupted, shutting down");
            Thread.currentThread().interrupt(); // Restore interrupted status
        } catch (Exception e) {
            log.error("Unexpected error in JournalParser", e);
            EventBusManager.publish(new AppLogEvent("Please check jounral directory"));
        }
    }

    private void startReading() throws IOException, InterruptedException {
        log.info("Starting Journal Parser");

        try (WatchService watchService = FileSystems.getDefault().newWatchService()) {
            journalDir.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY, StandardWatchEventKinds.ENTRY_CREATE);

            Path currentFile = getLatestJournalFile();
            long lastPosition = 0;
            log.info("Monitoring {}", currentFile.getFileName());

            while (isRunning) {
                Thread.sleep(120);
                // Wait for file events with a timeout to check isRunning and interruptions
                WatchKey key = watchService.poll(1, TimeUnit.SECONDS);
                if (key == null) {
                    if (Thread.currentThread().isInterrupted() || !isRunning) {
                        log.info("Shutting down JournalParser due to interruption or stop signal");
                        return;
                    }
                    continue;
                }

                Path latestFile = getLatestJournalFile();
                if (!latestFile.equals(currentFile)) {
                    lastPosition = 0;
                    currentFile = latestFile;
                    log.info("Switched to new journal file: {}", currentFile.getFileName());
                }

                try (BufferedReader reader = Files.newBufferedReader(currentFile, StandardCharsets.UTF_8)) {
                    reader.skip(lastPosition);
                    String line;
                    boolean isFirstLineAfterSeek = (lastPosition == 0);

                    while ((line = reader.readLine()) != null) {
                        if (isFirstLineAfterSeek) {
                            if (line.length() > 0 && line.charAt(0) == '\uFEFF') {
                                line = line.substring(1);
                            }
                            isFirstLineAfterSeek = false;
                        }

                        if (line.isBlank()) {
                            lastPosition += line.getBytes(StandardCharsets.UTF_8).length + System.lineSeparator().getBytes(StandardCharsets.UTF_8).length;
                            continue;
                        }

                        try {
                            String sanitizedLine = line.replaceAll("[\\p{Cntrl}\\p{Cc}\\p{Cf}]", "").trim();
                            if (!sanitizedLine.startsWith("{")) {
                                continue;
                            }

                            if (!sanitizedLine.endsWith("}")) {
                                continue;
                            }

                            JsonElement element = GsonFactory.getGson().fromJson(sanitizedLine, JsonElement.class);
                            if (!element.isJsonObject()) {
                                lastPosition += line.getBytes(StandardCharsets.UTF_8).length + System.lineSeparator().getBytes(StandardCharsets.UTF_8).length;
                                continue;
                            }

                            JsonObject eventJson = element.getAsJsonObject();
                            if (eventJson.has("event")) {
                                String eventType = eventJson.get("event").getAsString();
                                BaseEvent event = EventRegistry.createEvent(eventType, eventJson);
                                if (event != null && !event.isExpired()) {
                                    EventBusManager.publish(event);
                                    EventBusManager.publish(new AppLogEvent("Processing Event: " + eventType));
                                    log.info("Processing Journal Event: {} {}", eventType, event.toJsonObject());
                                } else if (event != null && event.isExpired()) {
                                    log.warn("Skipping event: {}, reason {}", eventType, "Event expired");
                                }
                            }
                        } catch (Exception e) {
                            log.error("Corrupted Journal File: {}", line);
                        }

                        lastPosition += line.getBytes(StandardCharsets.UTF_8).length + System.lineSeparator().getBytes(StandardCharsets.UTF_8).length;
                    }
                } catch (IOException e) {
                    EventBusManager.publish(new AiVoxResponseEvent("Error reading journal: " + e.getMessage()));
                    log.error("Error reading journal: {}", e.getMessage(), e);
                }

                key.reset();
            }
        }
    }

    private Path getLatestJournalFile() throws IOException {
        return Files.list(journalDir)
                .filter(p -> p.toString().endsWith(".log"))
                .max(Comparator.comparingLong(p -> p.toFile().lastModified()))
                .orElseThrow(() -> new IOException("No journal files found in " + journalDir));
    }
}