package elite.intel.gameapi;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import elite.intel.ai.mouth.subscribers.events.AiVoxResponseEvent;
import elite.intel.gameapi.journal.EventRegistry;
import elite.intel.gameapi.journal.events.BaseEvent;
import elite.intel.session.PlayerSession;
import elite.intel.ui.controller.ManagedService;
import elite.intel.ui.event.AppLogDebugEvent;
import elite.intel.util.json.GsonFactory;
import elite.intel.ws.WebSocketBroadcaster;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.SeekableByteChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.Comparator;

/**
 * The JournalParser class is responsible for monitoring and parsing journal log files
 * generated by the Elite Dangerous game. It continuously watches a specified directory
 * for changes to log files, reads journal entries, processes event data, and publishes
 * events to the EventBusManager for further handling.
 * <p>
 * This class is implemented as a Runnable to allow asynchronous execution in a separate
 * thread. It uses a WatchService to detect file modifications or new files in the directory
 * and processes journal data incrementally. Parsing includes handling JSON-based event data
 * and publishing it to the event bus for downstream processing.
 * <p>
 * Key Features:
 * - Watches a specified directory for log file creation and modification.
 * - Reads and processes journal entries with support for handling UTF-8 BOM.
 * - Publishes parsed event objects to a central event bus for handling.
 * - Handles safe shutdown and interruption of the parser thread.
 * <p>
 * Threading Behavior:
 * - The class relies on a dedicated worker thread started via the start method.
 * - The stop method is used to request the thread to terminate, ensuring a clean shutdown.
 * <p>
 * Error Handling:
 * - Catches and logs exceptions such as I/O issues or unexpected parsing errors.
 * - Publishes error-related events (e.g., AppLogEvent) to notify other components.
 */
public class JournalParser implements Runnable, ManagedService {
    private static final Logger log = LogManager.getLogger(JournalParser.class);
    private Path journalDir;
    private Thread processingThread;
    private volatile boolean isRunning;
    private final WebSocketBroadcaster webSocketBroadcaster = WebSocketBroadcaster.getInstance();

    public JournalParser() {
    }

    public synchronized void start() {
        journalDir = PlayerSession.getInstance().getJournalPath();
        if (processingThread != null && processingThread.isAlive()) {
            log.warn("JournalParser is already running");
            return;
        }
        isRunning = true;
        processingThread = new Thread(this, "JournalParserThread");
        processingThread.start();
        log.info("JournalParser started");
    }

    public synchronized void stop() {
        if (processingThread == null || !processingThread.isAlive()) {
            log.warn("JournalParser is not running");
            return;
        }
        isRunning = false;
        processingThread.interrupt();
        try {
            processingThread.join(5000); // Wait up to 5 seconds for clean shutdown
            log.info("JournalParser stopped");
        } catch (InterruptedException e) {
            log.warn("Interrupted while waiting for JournalParser to stop");
            Thread.currentThread().interrupt(); // Restore interrupted status
        }
        processingThread = null;
    }

    @Override
    public void run() {
        try {
            startReading();
        } catch (IOException e) {
            log.error("IOException in JournalParser", e);
            EventBusManager.publish(new AppLogDebugEvent("Please check journal directory"));
        } catch (InterruptedException e) {
            log.info("JournalParser interrupted, shutting down");
            Thread.currentThread().interrupt(); // Restore interrupted status
        } catch (Exception e) {
            log.error("Unexpected error in JournalParser", e);
            EventBusManager.publish(new AppLogDebugEvent("Please check journal directory"));
        }
    }

    private void startReading() throws IOException, InterruptedException {
        log.info("Starting Journal Parser");

        try (WatchService watchService = FileSystems.getDefault().newWatchService()) {
            journalDir.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY, StandardWatchEventKinds.ENTRY_CREATE);

            // If the app is started before the game, no journal exists yet. Wait for one.
            Path currentFile = null;
            boolean journalWarningSpoken = false;
            while (isRunning && currentFile == null) {
                try {
                    currentFile = getLatestJournalFile();
                } catch (IOException e) {
                    if (!journalWarningSpoken) {
                        log.info("No journal file found yet - waiting for game to start...");
                        EventBusManager.publish(new AiVoxResponseEvent("Commander, no game session detected. Standing by."));
                        journalWarningSpoken = true;
                    }
                    Thread.sleep(2000);
                }
            }
            if (!isRunning) return;
            long lastPosition = 0;
            log.info("Monitoring {}", currentFile);

            while (isRunning) {
                Thread.sleep(200);

                if (Thread.currentThread().isInterrupted() || !isRunning) {
                    log.info("Shutting down JournalParser due to interruption or stop signal");
                    return;
                }

                // Fix for Windows (two bugs, same root cause: OS-cached directory-entry metadata)
                //
                // Bug 1 (fixed earlier): channel.size() returned a stale cached file size, so the
                //   read was gated behind a check that never became true. Fixed by reading directly.
                //
                // Bug 2 (this fix): File.lastModified() in getLatestJournalFile() returns stale
                //   cached values for a file being written by another process. Calling it on every
                //   poll caused the parser to switch to an older journal file (whose cached mtime
                //   appeared newer), reset lastPosition to 0, and read only expired events forever.
                //
                // Solution: do NOT call getLatestJournalFile() inside the loop. Instead watch for
                // ENTRY_CREATE events from the WatchService. That fires reliably when the game
                // starts a new journal, and is unaffected by stale mtime caching.
                WatchKey key = watchService.poll();
                if (key != null) {
                    for (WatchEvent<?> watchEvent : key.pollEvents()) {
                        if (watchEvent.kind() == StandardWatchEventKinds.ENTRY_CREATE) {
                            @SuppressWarnings("unchecked")
                            Path created = ((WatchEvent<Path>) watchEvent).context();
                            if (created.toString().endsWith(".log")) {
                                lastPosition = 0;
                                currentFile = journalDir.resolve(created);
                                log.info("Switched to new journal file: {}", currentFile.getFileName());
                            }
                        }
                    }
                    key.reset();
                }

                try (SeekableByteChannel channel = Files.newByteChannel(currentFile, StandardOpenOption.READ)) {
                    // Do NOT use channel.size() as a gate: on Windows the OS caches the
                    // directory-entry file size and may not reflect bytes written by the game
                    // for minutes at a time. Attempt a direct read from lastPosition instead \u2014
                    // the read syscall bypasses the cached size and reaches actual file data.
                    channel.position(lastPosition);
                    ByteBuffer buf = ByteBuffer.allocate(65536);
                    int bytesRead = channel.read(buf);
                    log.debug("poll: file={} pos={} read={}", currentFile.getFileName(), lastPosition, bytesRead);
                    if (bytesRead > 0) {
                        buf.flip();

                        // Decode and split on \n \u2014 handles both \n and \r\n line endings
                        String chunk = StandardCharsets.UTF_8.decode(buf).toString();
                        String[] parts = chunk.split("\n", -1);
                        boolean firstLine = (lastPosition == 0);

                        // All parts except the last are complete lines (terminated by \n).
                        // The last part is either empty (file ended with \n) or an incomplete
                        // line not yet flushed by the game \u2014 leave it for the next poll.
                        for (int i = 0; i < parts.length - 1; i++) {
                            String raw = parts[i];
                            // Advance by exact bytes: the raw part as stored in file + the \n
                            lastPosition += raw.getBytes(StandardCharsets.UTF_8).length + 1;

                            // Strip \r if the game wrote \r\n
                            String line = raw.endsWith("\r") ? raw.substring(0, raw.length() - 1) : raw;

                            // Strip UTF-8 BOM from the very first line of the file
                            if (firstLine) {
                                if (!line.isEmpty() && line.charAt(0) == '\uFEFF') line = line.substring(1);
                                firstLine = false;
                            }

                            if (line.isBlank()) continue;

                            try {
                                String sanitizedLine = line.replaceAll("[\\p{Cntrl}\\p{Cc}\\p{Cf}]", "").trim();
                                if (!sanitizedLine.startsWith("{") || !sanitizedLine.endsWith("}")) continue;

                                JsonElement element = GsonFactory.getGson().fromJson(sanitizedLine, JsonElement.class);
                                if (!element.isJsonObject()) continue;

                                JsonObject eventJson = element.getAsJsonObject();
                                if (eventJson.has("event")) {
                                    String eventType = eventJson.get("event").getAsString();
                                    BaseEvent event = EventRegistry.createEvent(eventType, eventJson);
                                    if (event != null && !event.isReplay() && !event.isExpired()) {
                                        EventBusManager.publish(event);
                                        webSocketBroadcaster.broadcast(event.toJson());
                                        EventBusManager.publish(new AppLogDebugEvent("\tProcessing Event: " + eventType));
                                        log.info("Processing Journal Event: {} {}", eventType, event.toJsonObject());
                                    } else if (event != null && event.isReplay()) {
                                        log.debug("Skipping replay event: {}", eventType);
                                    } else if (event != null && event.isExpired()) {
                                        log.warn("Skipping event: {}, reason {}", eventType, "Event expired");
                                    }
                                }
                            } catch (Exception e) {
                                log.warn("Skipping malformed journal line: {} - {}", line, e.getMessage());
                            }
                        }
                    }
                } catch (IOException e) {
                    EventBusManager.publish(new AiVoxResponseEvent("Error reading journal: " + e.getMessage()));
                    log.error("Error reading journal: {}", e.getMessage(), e);
                }

            }
        }
    }

    private Path getLatestJournalFile() throws IOException {
        return Files.list(journalDir)
                .filter(p -> p.toString().endsWith(".log"))
                .max(Comparator.comparingLong(p -> p.toFile().lastModified()))
                .orElseThrow(() -> new IOException("No journal files found in " + journalDir));
    }
}