CREATE TABLE IF NOT EXISTS commodities (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    commodity TEXT NOT NULL UNIQUE
);

INSERT OR IGNORE INTO commodities (commodity)
VALUES ('Advanced Catalysers'),
    ('Advanced Medicines'),
    ('Agronomic Treatment'),
    ('AI Relics'),
    ('Alexandrite'),
    ('Aluminium'),
    ('Animal Meat'),
    ('Animal Monitors'),
    ('Anomaly Particles'),
    ('Antimatter Containment Unit'),
    ('Antique Jewellery'),
    ('Antiquities'),
    ('Articulation Motors'),
    ('Assault Plans'),
    ('Atmospheric Processors'),
    ('Auto-Fabricators'),
    ('Bauxite'),
    ('Battle Weapons'),
    ('Beer'),
    ('Benitoite'),
    ('Beryllium'),
    ('Bioreducing Lichen'),
    ('Bismuth'),
    ('Black Box'),
    ('Bone Fragments'),
    ('Bootleg Liquor'),
    ('Building Fabricators'),
    ('Ceramic Composites'),
    ('Chemical Waste'),
    ('Chemicals'),
    ('Clothing'),
    ('CMM Composite'),
    ('Cobalt'),
    ('Coffee'),
    ('Coltan'),
    ('Combat Stabilisers'),
    ('Commercial Samples'),
    ('Computer Components'),
    ('Conductive Fabrics'),
    ('Consumer Technology'),
    ('Coral Sap'),
    ('Crop Harvesters'),
    ('Cryolite'),
    ('Cyst Specimen'),
    ('Damaged Escape Pod'),
    ('Data Core'),
    ('Diplomatic Bag'),
    ('Domestic Appliances'),
    ('Earth Relics'),
    ('Emergency Power Cells'),
    ('Encrypted Correspondence'),
    ('Encrypted Data Storage'),
    ('Energy Grid Assembly'),
    ('Exhaust Manifold'),
    ('Evacuation Shelter'),
    ('Explosives'),
    ('Fish'),
    ('Food Cartridges'),
    ('Fossil Remnants'),
    ('Fruit and Vegetables'),
    ('Gallium'),
    ('Gallite'),
    ('Gene Bank'),
    ('Geological Equipment'),
    ('Geological Samples'),
    ('Gold'),
    ('Grain'),
    ('Grandidierite'),
    ('Guardian Casket'),
    ('Guardian Orb'),
    ('Guardian Relic'),
    ('Guardian Tablet'),
    ('Guardian Totem'),
    ('Guardian Urn'),
    ('H.E. Suits'),
    ('HN Shock Mount'),
    ('Haematite'),
    ('Hafnium 178'),
    ('Hardware Diagnostic Sensor'),
    ('Heatsink Interlink'),
    ('Hostages'),
    ('Hydrogen Fuel'),
    ('Hydrogen Peroxide'),
    ('Imperial Slaves'),
    ('Indium'),
    ('Indite'),
    ('Insulating Membrane'),
    ('Ion Distributor'),
    ('Jadeite'),
    ('Land Enrichment Systems'),
    ('Lanthanum'),
    ('Large Survey Data Cache'),
    ('Leather'),
    ('Legal Drugs'),
    ('Lepidolite'),
    ('Liquid Oxygen'),
    ('Liquor'),
    ('Lithium'),
    ('Lithium Hydroxide'),
    ('Low Temperature Diamonds'),
    ('Magnetic Emitter Coil'),
    ('Marine Equipment'),
    ('Methane Clathrate'),
    ('Methanol Monohydrate Crystals'),
    ('Meta-Alloys'),
    ('Micro Controllers'),
    ('Microbial Furnaces'),
    ('Micro-weave Cooling Hoses'),
    ('Military Intelligence'),
    ('Military Plans'),
    ('Mineral Extractors'),
    ('Mineral Oil'),
    ('Moissanite'),
    ('Modular Terminals'),
    ('Mollusc Brain Tissue'),
    ('Mollusc Fluid'),
    ('Mollusc Membrane'),
    ('Mollusc Mycelium'),
    ('Mollusc Soft Tissue'),
    ('Mollusc Spores'),
    ('Monazite'),
    ('Musgravite'),
    ('Nanobreakers'),
    ('Narcotics'),
    ('Natural Fabrics'),
    ('Neofabric Insulation'),
    ('Nerve Agents'),
    ('Non-Lethal Weapons'),
    ('Onionhead Gamma Strain'),
    ('Osmium'),
    ('Painite'),
    ('Palladium'),
    ('Performance Enhancers'),
    ('Personal Effects'),
    ('Personal Weapons'),
    ('Pesticides'),
    ('Platinum'),
    ('Pod Core Tissue'),
    ('Pod Dead Tissue'),
    ('Pod Mesoglea'),
    ('Pod Outer Tissue'),
    ('Pod Shell Tissue'),
    ('Pod Surface Tissue'),
    ('Pod Tissue'),
    ('Political Prisoners'),
    ('Polymers'),
    ('Power Converter'),
    ('Power Generators'),
    ('Power Transfer Bus'),
    ('Praseodymium'),
    ('Precious Gems'),
    ('Progenitor Cells'),
    ('Prohibited Research Materials'),
    ('Prototype Tech'),
    ('Pyrophyllite'),
    ('Radiation Baffle'),
    ('Rare Artwork'),
    ('Reactive Armour'),
    ('Rebel Transmissions'),
    ('Reinforced Mounting Plate'),
    ('Resonating Separators'),
    ('Rhodplumsite'),
    ('Robotics'),
    ('Rockforth Fertiliser'),
    ('Rutile'),
    ('Samarium'),
    ('Scrap'),
    ('Semiconductors'),
    ('Serendibite'),
    ('Silver'),
    ('Slaves'),
    ('Small Survey Data Cache'),
    ('Space Pioneer Relics'),
    ('Steel'),
    ('Structural Regulators'),
    ('Superconductors'),
    ('Surface Stabilisers'),
    ('Survival Equipment'),
    ('Synthetic Fabrics'),
    ('Synthetic Meat'),
    ('Synthetic Reagents'),
    ('Tactical Data'),
    ('Taaffeite'),
    ('Tantalum'),
    ('Tea'),
    ('Technical Blueprints'),
    ('Telemetry Suite'),
    ('Thermal Cooling Units'),
    ('Thallium'),
    ('Thargoid Basilisk Tissue Sample'),
    ('Thargoid Bio-storage Capsule'),
    ('Thargoid Biological Matter'),
    ('Thargoid Cyclops Tissue Sample'),
    ('Thargoid Glaive Tissue Sample'),
    ('Thargoid Heart'),
    ('Thargoid Hydra Tissue Sample'),
    ('Thargoid Link'),
    ('Thargoid Medusa Tissue Sample'),
    ('Thargoid Orthrus Tissue Sample'),
    ('Thargoid Probe'),
    ('Thargoid Resin'),
    ('Thargoid Scout Tissue Sample'),
    ('Thargoid Scythe Tissue Sample'),
    ('Thargoid Sensor'),
    ('Thargoid Technology Samples'),
    ('Thorium'),
    ('Time Capsule'),
    ('Titan Deep Tissue Sample'),
    ('Titan Drive Component'),
    ('Titan Maw Deep Tissue Sample'),
    ('Titan Maw Partial Tissue Sample'),
    ('Titan Maw Tissue Sample'),
    ('Titan Partial Tissue Sample'),
    ('Titan Tissue Sample'),
    ('Tobacco'),
    ('Toxic Waste'),
    ('Trade Data'),
    ('Trinkets of Hidden Fortune'),
    ('Tritium'),
    ('Unclassified Relic'),
    ('Unoccupied Escape Pod'),
    ('Unstable Data Core'),
    ('Uranium'),
    ('Void Opal'),
    ('Water'),
    ('Weapons'),
    ('Wine');