INSERT OR IGNORE INTO material_names (name)
VALUES ('Alexandrite'),
    ('Bauxite'),
    ('Benitoite'),
    ('Bertrandite'),
    ('Bromellite'),
    ('Cobalt'),
    ('Coltan'),
    ('Gallite'),
    ('Grandidierite'),
    ('Hydrogen Peroxide'),
    ('Indite'),
    ('Lepidolite'),
    ('Liquid oxygen'),
    ('Lithium Hydroxide'),
    ('Low Temperature Diamonds'),
    ('Methane Clathrate'),
    ('Methanol Monohydrate Crystals'),
    ('Monazite'),
    ('Musgravite'),
    ('Painite'),
    ('Platinum'),
    ('Praseodymium'),
    ('Rhodplumsite'),
    ('Rutile'),
    ('Samarium'),
    ('Serendibite'),
    ('Tritium'),
    ('Uraninite'),
    ('Void Opal'),
    ('Water');